FROM ttux/alpine-lib-ready

# ENV NODE_VERSION v4.1.1
# ENV NODE_PATH /opt/runtime/node-${NODE_VERSION}

# For base builds
# ENV CONFIG_FLAGS="--without-npm" RM_DIRS=/usr/include
# ENV CONFIG_FLAGS="--fully-static --without-npm" RM_DIRS=${NODE_PATH}/include
# ENV DEL_PKGS="libgcc libstdc++"

COPY compile-node.sh /tmp/

ENTRYPOINT /tmp/compile-node.sh
