noderuntime-builder:
  build: .
  dockerfile: Dockerfile.nodebuilder
  volumes:
    - ./node-runtime:/opt/runtime
  working_dir: /tmp
  entrypoint: /tmp/compile-node.sh
nodenpm-builder:
  build: .
  dockerfile: Dockerfile.nodenpm
  volumes:
    - ./nodeapp/YOURNODEAPP:/opt/app
    - ./node-runtime:/opt/runtime:ro
  entrypoint:
    - /tmp/build-npm.sh
YOURNODEAPP:
  build: .
  dockerfile: Dockerfile.nodeapp
  working_dir: /opt/app
  command: npm start
  volumes:
    - ./nodeapp/YOURNODEAPP:/opt/app:ro
    - ./node-runtime:/opt/runtime:ro
  ports:
    - "127.0.0.1:3000:3000"
