noderuntime-builder:
  build: .
  dockerfile: Dockerfile.nodebuilder
  volumes:
    - ./node-runtime:/opt/runtime
  working_dir: /tmp
  entrypoint: /tmp/compile-node.sh
nodenpm-builder:
  build: .
  dockerfile: Dockerfile.nodenpm
  volumes:
    - ./nodeapp:/opt/app
    - ./node-runtime:/opt/runtime:ro
nodeapp:
  build: .
  dockerfile: Dockerfile.nodeapp
  working_dir: /opt/app
  volumes:
    - ./nodeapp:/opt/app
    - ./node-runtime:/opt/runtime:ro
  ports:
    - "3000:3000"
